config/routes.rb
Trendy::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show] do 
    member do
      get "favourites", to: "users#favourites"
    end
  end

  resources :users, :only => [:index, :show] do
    resources :follows, :only => [:create, :destroy]
  end

  resources :widgets do
    member do
      put "like", to: "widgets#like"
      put "unlike", to: "widgets#unlike"
    end
  end
  
  mount Commontator::Engine => '/commontator'

  resource :buckets, except: [:new, :edit, :show, :update]

  root :to => "widgets#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_commontator
  has_merit
  mount_uploader :avatar, AvatarUploader
  acts_as_voter

  acts_as_follower
  acts_as_followable


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true

  has_many :authorizations

  has_many :widgets, through: :buckets
  has_many :buckets

   # Send a welcome email after the user has been created
  after_create { |u| u.send_email(:welcome) }

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login, :avatar, :avatar_cache, :remove_avatar
  # attr_accessible :title, :body

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  # Sends an email to the user, using the unique identifier
  # for the email template. All Emails are enqueued as a
  # {UserMailerJob} and subsequently processed by a worker
  # in the {UserMailer} class.
  #
  # @param [Symbol] key of the email to send to the user.
  def send_email(key)
    job = UserMailerJob.new(key.to_sym, id)
    Delayed::Job.enqueue job
  end

  # bypasses Devise's requirement to re-enter current password to edit
  def update_with_password(params={}) 
    if params[:password].blank? 
      params.delete(:password) 
      params.delete(:password_confirmation) if params[:password_confirmation].blank? 
    end 
    update_attributes(params) 
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
	  @user = User.find(params[:id])
	end

	def favourites
	  @user = User.find(params[:id])
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/favourites.html.erb
<div class="container">
    <div id="container">

    <% @user.find_liked_items.each do |widget| %>

       <% if widget.media == "photo" %>
            
        <div class="item">

            <%= link_to widget_path(widget) do %>



            <div class="img-container">
                <div class="open-icon png-icon">
                    <img src="<%= image_path "open.png" %>">
                </div>
                <div class="image" style="background-image:url('<%= widget.content %>')"></div>
            </div>

            <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>

           

            <% end %>

            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span><%= widget.impressionist_count %></p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>


           




        </div>

        <% end %>

        <% if widget.media == "video" %>
        <div class="item video-item">

            <%= link_to widget_path(widget) do %>
                
                <div class="video-container"> 
                    <div class="open-icon png-icon">
                        <img src="<%= image_path "play.png" %>">
                    </div>
                    <div class="video" style="background-image:url('<%= widget.thumb %>')"></div>
                </div>

                <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>
                

            <% end %>

            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span><%= widget.impressionist_count %></p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>
        
        </div>

        <% end %>

        <% if widget.media == "rich" %>

                <div class="item">

            <%= link_to widget_path(widget) do %>



            <div class="img-container">
                <div class="open-icon png-icon">
                    <img src="<%= image_path "audio.png" %>">
                </div>
                <div class="image" style="background-image:url('<%= widget.thumb %>')"></div>
            </div>

            <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>

           

            <% end %>

            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span><%= widget.impressionist_count %></p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>


        <% end %>


        <% if widget.media == "link" %>

        <div class="item">

            <%= link_to widget.url, target: "_blank" do %>
            
            <div class="img-container">
                <div class="open-icon png-icon">
                    <img src="<%= image_path "link.png" %>">
                </div>
                <div class="image" style="background-image:url('<%= widget.thumb %>')"></div>
            </div>

            <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>


            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Source</p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>

        </div>


        <% end %>

       


        <% end %>


    </div>
</div>





<script>
    $("#container").gridalicious({
      gutter: 40,
      width: 335,
      animate: true,
      animationOptions: {
        queue: true,
        speed: 200,
        duration: 300,
        effect: 'fadeInOnAppear',
      }
    });
</script>

app/views/users/show.html.erb
<div class="profile-top">
    <div class="row">

        <% if user_signed_in? %>
          <div id="follow_user">
            <%= render :partial => "shared/follow_user", :locals => {:user => @user} %>
          </div>
        <% end %>

        <div class="col-md-4 text-center">
            <div class="user-likes">
                <p><span class="icon">n</span><%= @user.find_liked_items.count %></p>
            </div>
        </div>

        <div class="col-md-4 text-center">
            <div class="profile-user-avatar" style="background-image:url('<%= @user.avatar %>')">
            </div>
            <h2><%= @user.username %></h2>
        </div>

        <div class="col-md-4 text-center">
            <div class="user-points">
                <p><span class="icon">H</span><%= @user.points %></p>
            </div>
        </div>

    </div>


</div>

<div class="container">
    <div id="container">

        <% @user.find_liked_items.each do |widget| %>

         <% if widget.media == "photo" %>
            
        <div class="item">

            <%= link_to widget_path(widget) do %>



            <div class="img-container">
                <div class="open-icon png-icon">
                    <img src="<%= image_path "open.png" %>">
                </div>
                <div class="image" style="background-image:url('<%= widget.content %>')"></div>
            </div>

            <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>

           

            <% end %>

            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span><%= widget.impressionist_count %></p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>


           




        </div>

        <% end %>

        <% if widget.media == "video" %>
        <div class="item video-item">

            <%= link_to widget_path(widget) do %>
                
                <div class="video-container"> 
                    <div class="open-icon png-icon">
                        <img src="<%= image_path "play.png" %>">
                    </div>
                    <div class="video" style="background-image:url('<%= widget.thumb %>')"></div>
                </div>

                <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>
                

            <% end %>

            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span><%= widget.impressionist_count %></p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>
        
        </div>

        <% end %>

        <% if widget.media == "rich" %>

                <div class="item">

            <%= link_to widget_path(widget) do %>



            <div class="img-container">
                <div class="open-icon png-icon">
                    <img src="<%= image_path "audio.png" %>">
                </div>
                <div class="image" style="background-image:url('<%= widget.thumb %>')"></div>
            </div>

            <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>

           

            <% end %>

            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span><%= widget.impressionist_count %></p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>
        </div>


        <% end %>


        <% if widget.media == "link" %>

        <div class="item">

            <%= link_to widget.url, target: "_blank" do %>
            
            <div class="img-container">
                <div class="open-icon png-icon">
                    <img src="<%= image_path "link.png" %>">
                </div>
                <div class="image" style="background-image:url('<%= widget.thumb %>')"></div>
            </div>

            <div class="widget-info">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-12">               
                            <h3><%= widget.title %></h3>
                            <p><%= widget.description %></p>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="widget-user-avatar">
                                <div class="avatar" style="background-image:url('<%= widget.user.avatar %>')"></div>
                            </div>
                            <h2><a href="/users/<%= widget.user.id %>"><%= widget.username %></a></h2>
                        </div>
                    </div>
                </div>
            </div>
            <% end %>


            <div class="widget-stats">
                <div class="container-fluid">

                    <div class="row widget-post-stats">
                        <div class="col-md-4 text-center">
                            <% if current_user && current_user.voted_for?(widget) %>
                                <p class="heart-icon-liked"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% else %>
                                <p class="heart-icon"><span class="icon">n</span><%= widget.get_likes.size %></p>
                            <% end %>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Source</p>
                        </div>

                        <div class="col-sm-4 text-center">
                            <p class="comment-icon"><span class="icon">k</span>Share</p>
                        </div>
                    </div>

                </div>
            </div>

        </div>


        <% end %>

       


        <% end %>


    </div>
</div>





<script>
    $("#container").gridalicious({
      gutter: 40,
      width: 335,
      animate: true,
      animationOptions: {
        queue: true,
        speed: 200,
        duration: 300,
        effect: 'fadeInOnAppear',
      }
    });
</script>