config/routes.rb
Trendy::Application.routes.draw do
  
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show] do 
    member do
      get "favourites", to: "users#favourites"
    end
  end

  resources :users, :only => [:index, :show] do
    resources :follows, :only => [:create, :destroy]
  end

  resources :widgets do
    member do
      put "like", to: "widgets#like"
      put "unlike", to: "widgets#unlike"
    end
  end
  
  mount Commontator::Engine => '/commontator'

  resource :buckets, except: [:new, :edit, :show, :update]

  root :to => "widgets#index"
end

app/models/widget.rb
class Widget < ActiveRecord::Base
  attr_accessible :content, :ident, :source, :title, :media, :url, :tag_list, :thumb, :username, :description
  acts_as_commontable
  acts_as_votable
  is_impressionable
  
  belongs_to :user 
  validates_presence_of :user


  def next
    self.class.where("id > ?", id).first
  end

  def prev_six
    self.class.where("id < ?", id).reverse.slice(0,6)
  end

  def prev
    self.class.where("id < ?", id).last
  end

  def populate!
  	data = $embedly.oembed(url: url)
  	widget = data[0]

    # Content of the title "Miley Cyrus Twerks"
  	self.title = widget.title if self.title == nil || self.title == ""
    # Photo, Video, Audio
  	self.media = widget.type
    # Vine, Instagram, Vimeo
  	self.source = widget.provider_name.downcase
    # Thumbnail
    self.thumb = widget.thumbnail_url
    # Thumbnail
    self.favicon = widget.favicon_url
    # Description
    self.description = widget.description if self.description == nil || self.description == ""


  	self.content = case media
  	when "video"
  		widget.html
    when "rich"
      widget.html
  	when "image"
  	when "photo"
  		widget.url
  	end

  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  # GET /widgets
  # GET /widgets.json

  impressionist :actions=>[:show]

  def index

    @widgets = Widget.order(order).paginate(:page => params[:page], :per_page => 20)
    
    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @widgets }
    end
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    @widget = Widget.find(params[:id])
    commontator_thread_show(@widget)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/new
  # GET /widgets/new.json
  def new
    @widget = Widget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
    authorize! :edit, @widget
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(params[:widget])

    @widget.user = current_user
    @widget.username = current_user.username


    @widget.populate!

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render json: @widget, status: :created, location: @widget }
      else
        format.html { render action: "new" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /widgets/1
  # PUT /widgets/1.json
  def update
    authorize! :update, @widget
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget = Widget.find(params[:id])
    authorize! :destroy, @widget
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end

  def like
    @widget = Widget.find(params[:id])
    @widget.liked_by current_user
    redirect_to @widget
  end


  def unlike
    @widget = Widget.find(params[:id])
    @widget.unliked_by current_user
    redirect_to @widget
  end

  

  def order

    ordering = case params[:order]
    when 'newest'
      'created_at'
    when 'popular'
      'cached_votes_total'
    else
      'created_at'
    end

    ordering = case params[:order_by]
    when 'desc'
      ordering + ' DESC'
    when 'asc'
      ordering + ' ASC'
    else
      ordering + ' DESC'
    end

    ordering
  end

  

end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_form.html.erb
<div class="container-fluid widget-create">
  <div class="background"></div>
  <div class="row">

  </div>

  <div class="row">
    <div class="col-md-12">
      <h1>Submit Post</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <p>Submit a post below, enter a URL to get started. Give your post a title and a description - if one isn't supplied we will fetch it from the site.</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
     <%= form_for(@widget) do |f| %>

      <% if @widget.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

          <ul>
          <% @widget.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

        <%= f.text_field :url, :autofocus => true, :placeholder => "http://replacethisurl.com" %>
        <%= f.text_field :title, :placeholder => "Post Title" %>
        <%= f.text_area :description, :placeholder => "Enter a description for this post. Be nice!" %>

    </div>
  </div>


  <div class="row">
    <div class="col-md-12 sign-up-button">
      <%= f.submit %>
    </div>
  </div>

</div>

<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<% title "Home" %>
<div class="container-fluid">

    <!-- START OF INTRODUCTION BOX -->
<% if user_signed_in? %>

<% else %>
    <div class="row introduction">
        <div class='container'>
        <div class="col-md-12">
            <div class="row">

                <div class="col-md-6 col-md-offset-3 text-center">
                    <h1>Share the links you love, easily</h1>
                    <p>Hashtagg is the best way to share your favourite </br>links from across the web</p>
                    <%= link_to "Sign up for Hashtagg", new_user_registration_path, class: "btn btn-primary"  %>
                </div>


            </div>
        </div>
        </div>
    </div>
<% end %>
</div>

<!-- END OF INTRODUCTION BOX -->

<div class="container-fluid sorting">
    <!-- START OF SORTING BAR -->
    <div class="row">
        <div class="container">
            <div class="col-md-12">
                <ul class="clearfix">
                    <li>
                        <%= link_to root_path(:order => 'popular'), class: "editor" do %>
                          Popular
                        <% end %>
                    </li>
                    <li>
                        <a href="#" class="commented">Following</a>
                    </li>
                    <li>
                        <%= link_to root_path(:order => 'newest'), class: "trending" do %>
                          Groups
                        <% end %>
                    </li>
                    
                    <li>
                     <% if user_signed_in? %>

                        <%= link_to new_widget_path, class: "btn btn-new" do  %>
                            <i class="md-create md-5x"></i>
                        <% end %>

                    <% else %>

                        <%= link_to "Register to Post", new_user_registration_path, class: "btn btn-register"  %>

                    <% end %>
                        
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="container feed-container">

    <div id="container">

<%= render 'layouts/feed' %>

    </div>
</div>

<%= will_paginate @widgets %>

<!--
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
            </div>
        </div>
    </div>
-->  
<br />

<script>
    $("#container").gridalicious({
      gutter: 40,
      width: 300,
      animate: true,
      animationOptions: {
        queue: true,
        speed: 200,
        duration: 300,
        effect: 'fadeInOnAppear',
      }
    });
</script>

app/views/widgets/index.js.erb
//$('#container').append("<%=j render(partial: 'layouts/feed', format: 'html') %>");
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@widgets) %>');

$('#container').gridalicious('append', $("<%=j render(partial: 'layouts/feed', format: 'html') %>"));

app/views/widgets/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<% title @widget.title %>
<div class="container inpost-header">

  <div class="row inpost-content-wrapper">

    <% if @widget.media == "photo" %>
      <div class="col-md-12 text-center">
              <img src="<%= @widget.content %>" id="show-image" class="image"/>
      </div>
    <% end %>

    <% if @widget.media == "video" %>
      <div class="col-md-12 content text-center">
              <%= raw @widget.content %>
      </div>
    <% end %>

    <% if @widget.media == "rich" %>
      <div class="col-md-12 content text-center">
              <%= raw @widget.content %>
      </div>
    <% end %>

    <% if @widget.media == "link" %>
      <div class="col-md-12 content text-center">
        <img src="<%= @widget.thumb %>" id="show-image" class="image"/>
      </div>
    <% end %>

  </div>






    <div class="row widget-name">
      <div class="col-md-12">
        <h2><%= @widget.title %></h2>
      </div>
    </div>

    <div class="row widget-user">
      <div class="col-md-12">
        <div class="in-post-avatar" style="background-image:url('<%= @widget.user.avatar %>')"></div>
        <p><a href="/users/<%= @widget.user.id %>"><%= @widget.username %></a></p>
      </div>
    </div>

    <div class="row widget-functions">
      <div class="col-md-2">
        <% if current_user && current_user.voted_for?(@widget) %>
              <%= link_to ("<span class='icon'>n</span> Liked").html_safe, unlike_widget_path(@widget), class: "btn btn-loved", method: :put %>
        <% else %>
              <%= link_to ("<span class='icon'>n</span> Like?").html_safe, like_widget_path(@widget), class: "btn btn-love", method: :put %>  
        <% end %>
      </div>

      <div class="col-md-3">
        <%= link_to ("<span class='icon'>p</span>Comments").html_safe, @widget.url, class: "btn btn-comment"  %>
      </div>

      <div class="col-md-3">
        <%= link_to ("<span class='icon'>&#xe011;</span>Share").html_safe, @widget.url, class: "btn btn-share"  %>
      </div>

    </div>

    <div class="row widget-description">
      <div class="col-md-12">
        <p><%= @widget.description %></p>
      </div>
    </div>





<!--       <div class="col-md-8">

      </div> -->

    <div class="row widget-comments">
      <div class="col-md-12">
        <%= commontator_thread(@widget) %>
      </div>
    </div>

     
</div>

<div class="container">
    <div class="row">
      <div class="col-md-12 text-center delete-links">
          <% if can? :update, @widget %>
            <%= link_to "Edit", edit_widget_path(@widget) %>
            <%= link_to "Delete", @widget, :method => :delete, :confirm => "Are you sure ?"%>
          <% end %>
      </div>
    </div>
</div>







<p id="notice"><%= notice %></p>